# Without .PHONY: create a directory called `test` and `make test` stops working.
#   mkdir test && make test   ->  make: 'test' is up to date.
# Uncomment the next line and try again.
# .PHONY: test

test:
	@echo "running tests..."
